name: Flight Bot

on:
    schedule:
        - cron: "*/20 * * * *" # 20분 마다

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: "18.x"

            - name: Install Dependencies
              run: npm ci

            - name: Run Main Program
              run: npm start
              env:
                  NEIS_KEY: ${{ secrets.SLACK_TOKEN }}
