name: NodeJS with Webpack

on:
    push:
        branches: ["main"]
    schedule:
        - cron: "*/20 * * * *" # 20분마다

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [18.x]

        steps:
            - uses: actions/checkout@v3

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"

            - name: Run
              run: |
                  npm ci
                  npm start
              env:
                  SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
                  S3_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
                  S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
